# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GLASS_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GLASS_iOS

  #Pods for Using Alamofire
  pod 'Alamofire', '~> 5.4'

  #Pods for KeyChain
  use_frameworks!
  pod 'KeychainAccess'

end
