# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GLASS_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GLASS_iOS

  pod 'Alamofire', '~> 5.4'
  pod 'KeychainAccess'
  pod 'Kingfisher' 
  pod 'SnapKit'

end
